replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "0.2.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: ""
  extraAnnotations: {}
  hosts:
    - path: /
      pathType: Prefix
